[package]
name = "winapi-user32"
version = "0.1.0"
authors = ["Michael Graf"]
publish = false

[dependencies]
winapi_typedefs = { package="winapi-typedefs", git = "https://github.com/bitminded/rs-winapi-typedefs.git" }

[lib]
name = "winapi_user32"
path = "src/lib.rs"
